/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {
        initComponents();

tidak2.setVisible(false);
tidak3.setVisible(false);




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ya = new javax.swing.JButton();
        tidak2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tidak3 = new javax.swing.JButton();
        tidak1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ya.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ya.setText("YA");
        ya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yaMouseEntered(evt);
            }
        });

        tidak2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tidak2.setText("TIDAK");
        tidak2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tidak2MouseEntered(evt);
            }
        });
        tidak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidak2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ILHAM JAYA SEORANG COWOK YANG GANTENG");

        tidak3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tidak3.setText("TIDAK");
        tidak3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tidak3MouseEntered(evt);
            }
        });
        tidak3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidak3ActionPerformed(evt);
            }
        });

        tidak1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tidak1.setText("TIDAK");
        tidak1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tidak1MouseEntered(evt);
            }
        });
        tidak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidak1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ya, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tidak3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tidak2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(356, 356, 356))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(610, Short.MAX_VALUE)
                    .addComponent(tidak1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(109, 109, 109)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(ya, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tidak3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(tidak2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(tidak1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(213, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tidak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidak2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidak2ActionPerformed

    private void tidak3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidak3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidak3ActionPerformed

    private void tidak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidak1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidak1ActionPerformed

    private void tidak1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidak1MouseEntered
tidak1.setVisible(false);
tidak2.setVisible(true);
    }//GEN-LAST:event_tidak1MouseEntered

    private void tidak2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidak2MouseEntered
tidak2.setVisible(false);
tidak3.setVisible(true);
    }//GEN-LAST:event_tidak2MouseEntered

    private void tidak3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tidak3MouseEntered
tidak3.setVisible(false);
tidak1.setVisible(true);
    }//GEN-LAST:event_tidak3MouseEntered

    private void yaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yaMouseEntered
tidak1.setVisible(true);
tidak2.setVisible(false);
tidak3.setVisible(false);
    }//GEN-LAST:event_yaMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton tidak1;
    private javax.swing.JButton tidak2;
    private javax.swing.JButton tidak3;
    private javax.swing.JButton ya;
    // End of variables declaration//GEN-END:variables
}
